# Generated by Django 6.0.4 on 2026-04-11 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое (Lexical JSON)')),
                ('yjs_state', models.BinaryField(blank=True, null=True, verbose_name='Состояние Yjs (Binary)')),
                ('order', models.FloatField(db_index=True, default=0)),
                ('current_version', models.IntegerField(default=1, verbose_name='Текущая версия')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wiki.wikipage', verbose_name='Родительская страница')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='spaces.space', verbose_name='Пространство')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
            ],
            options={
                'db_table': 'wiki_pages',
            },
        ),
        migrations.CreateModel(
            name='UserSyncState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client_yjs_version', models.IntegerField(default=0, verbose_name='Версия Yjs на клиенте')),
                ('is_offline', models.BooleanField(default=False, verbose_name='Потеряно соединение')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'db_table': 'user_sync_state',
            },
        ),
        migrations.CreateModel(
            name='PageMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=10, verbose_name='Роль')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'db_table': 'page_memberships',
            },
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='wiki.wikipage', verbose_name='Откуда')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='wiki.wikipage', verbose_name='Куда')),
            ],
            options={
                'db_table': 'page_links',
            },
        ),
        migrations.CreateModel(
            name='LinkedEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('entity_type', models.CharField(choices=[('datasheet', 'Таблица'), ('view', 'Представление'), ('record', 'Запись'), ('page', 'Страница')], max_length=20, verbose_name='Тип сущности')),
                ('mws_id', models.CharField(db_index=True, max_length=50, verbose_name='ID в MWS')),
                ('render_config', models.JSONField(default=dict, verbose_name='Настройки отображения')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_entities', to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'db_table': 'linked_entities',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('mark_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID mark-ноды из Lexical JSON')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wiki.comment', verbose_name='Родительский комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='WikiPageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('content', models.JSONField(verbose_name='Содержимое (Снапшот)')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий к версии')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'db_table': 'wiki_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['space', '-updated_at'], name='wiki_pages_space_i_0e9013_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['id'], name='wiki_pages_id_eb8d7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('space', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='usersyncstate',
            unique_together={('user', 'page')},
        ),
        migrations.AlterUniqueTogether(
            name='pagemembership',
            unique_together={('page', 'user')},
        ),
        migrations.AddIndex(
            model_name='pagelink',
            index=models.Index(fields=['target', 'source'], name='page_links_target__9522e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagelink',
            unique_together={('source', 'target')},
        ),
        migrations.AddIndex(
            model_name='linkedentity',
            index=models.Index(fields=['entity_type', 'mws_id'], name='linked_enti_entity__45abd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='linkedentity',
            unique_together={('page', 'entity_type', 'mws_id')},
        ),
        migrations.AlterUniqueTogether(
            name='wikipageversion',
            unique_together={('page', 'version_number')},
        ),
    ]
