# Generated by Django 6.0.4 on 2026-04-12 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_initial'),
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.UniqueConstraint(fields=('space', 'title'), name='unique_space_page_title'),
        ),
    ]
