# Generated by Django 6.0.4 on 2026-04-12 12:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_initial'),
        ('wiki', '0002_alter_wikipage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Вектор поиска'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='wiki_pages_search__80fcfb_gin'),
        ),
    ]
